server:
  port: 8090
spring:
  cloud:
    nacos:
      ## 注册中心配置
      discovery:
        # nacos的服务地址，nacos-server中IP地址:端口号
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: api_router
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
      ## 整合sentinel，配置sentinel控制台的地址
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

      scg:
        fallback:
          mode: response
          response-status: 200
          response-body: '{"code":429,"message":"被限流了！"}'
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-consumer
    protocol:
      name: dubbo
      port: 20881
  registry:
    address: nacos://localhost:8848
