server:
  port: 8123
  servlet:
    context-path: /api


api:
  client:
    access-key: sheldon
    secret-key: sheldon
spring:
  redis:
    database: 2
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
